services:

    database:
        image: arm64v8/postgres:16.2
        # image: postgres:13
        restart: unless-stopped
        volumes:
            - algo_introvert_database:/var/lib/postgresql/data:delegated
        ports:
            - "5432:5432"
        environment:
          - POSTGRES_DB=algo_introvert
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=introvert



# using this named volume ensures db's hang around between "up's"
volumes:
    algo_introvert_database:

